### ISSUE TITLE
Followed readme instructions but having issue displaying the questions and submitting answers

### ISSUE THREAD

**Issue by peterdoherty01** [bonartm/hugo-quiz#1]
I added the files to the said locations and cannot see the options; when I click submit I get no actions.

Note: I added this to my current theme and inserted the markdown shortcode. 

What could I be missing?

Thanks

![image](https://user-images.githubusercontent.com/22255078/78305831-ea0e8200-750f-11ea-9714-ca70c6f8f605.png)

**Comment by bonartm** [comment]
I've only tested it with the Learn Theme for Hugo. Do you get any errors in the web console when loading your page?

**Comment by shyamvalsan** [comment]
I think I see the same error, and see the following error in the console

Error: Error building site: <snip>: failed to extract shortcode: shortcode "quiz" has no .Inner, yet a closing tag was provided

**Comment by bonartm** [comment]
Closed due to inactivity.

**Comment by bonartm** [comment]
Please try out the most recent version 0e538e5 with Hugo version 0.57.2.
