### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by TheBarzFR** [bonartm/hugo-quiz#11]
Hello
Thanks for hugo and js scrips. Pretty cool !

Do you have any idea about a special needs:
I would like to do not display the scores to the candidate or any people.
The teacher or "admin" are only the person authorized to display the scores. It should be by sent mail ou just a thru a web page.

Thanks for your ideas !
Cheers

**Comment by bonartm** [comment]
> The quizzes are for fun and not for serious assessment. Since everything is rendered on the client side, the hints and solutions to the questions become visible once javascript is disabled in the browser.
