### ISSUE TITLE
Explanation for wrong answers

### ISSUE THREAD

**Issue by BITS-Editor** [bonartm/hugo-quiz#4]
Hi!

It would be great, if the quiz would allow to show explanations when a wrong answer was chosen.

**Comment by bonartm** [comment]
I implemented a really basic option for writing hints that appear after a wrong answer was chosen. Please see the [demo](https://bonartm.github.io/hugo-quiz/).

I tested it with hugo 0.80.0. Note, that the quiz syntax slightly updated. Check out the README for the updates. 

Note, that I'm currently working on a [new javascript quiz library](https://github.com/bonartm/quizdown-js) that allows you to write your quizzes with markdown and render it as html. I also plan to add optional features like further instructions or explanations. This makes the integration with hugo much nicer.

**Comment by BITS-Editor** [comment]
Thank you!

> I implemented a really basic option for writing hints that appear after a wrong answer was chosen. Please see the [demo](https://bonartm.github.io/hugo-quiz/).

In the demo, I can't see the the hints.
