### ISSUE TITLE
Cannot run local demo

### ISSUE THREAD

**Issue by mccartney** [bonartm/hugo-quiz#7]
(Sorry for my ignorance, this is the first time I hear of hugo, so I might be missing something totally obvious)

With [current master](https://github.com/bonartm/hugo-quiz/commit/0ad73fa39d997f195cda656235f32a5145fe64cc) when I:
```
cd demo
hugo server -D
```
the server starts, but serves an empty page:

```
$ wget -qO- "http://localhost:1313/hugo-quiz/"
<pre>
</pre>
```

**Comment by bonartm** [comment]
Please also run `git submodule update --init` from the root of the repo to clone the submodule that contains the hugo learn theme into `/hugo-quiz/demo/themes/hugo-theme-learn`. Also see:

- https://github.com/bonartm/hugo-quiz#demo
- https://gohugo.io/getting-started/quick-start/#step-3-add-a-theme
- https://learn.netlify.app/en/basics/installation/#install-the-theme
