### ISSUE TITLE
install

### ISSUE THREAD

**Issue by GerhardMes** [bonartm/hugo-quiz#8]
hi there, one thing I do not get. From where should I install (and to where) the "quizdown.js". Cannot find it. Or can't I see it. Or am I to stupid - it is already quick later here.

**Comment by Zackyist** [comment]
It seems to be located in its [own repository](https://github.com/bonartm/quizdown-js). I missed it myself at first, it's linked at the beginning of the readme. Perhaps a link should be added to the installation steps as well?

**Comment by bonartm** [comment]
Quizdown is a javascript library which is developed in a separated project. `hugo-quiz` uses a shortcode to use quizdown with Hugo. 

If you are using the `hugo-learn` theme you can create a file `/layouts/partials/custom-header.html` and only add the script tags to it. Check out [the demo](https://github.com/bonartm/hugo-quiz/blob/master/demo/layouts/partials/custom-header.html) in this repository.

In general, to install quizdown, you need to add the library to the head of your website:

```html
<head>
    ...
  <script 
     src="https://cdn.jsdelivr.net/npm/quizdown@latest/public/build/quizdown.js">
  </script>
  <script 
      src="https://cdn.jsdelivr.net/npm/quizdown@latest/public/build/extensions/quizdownKatex.js">
  </script>
  <script 
      src="https://cdn.jsdelivr.net/npm/quizdown@latest/public/build/extensions/quizdownHighlight.js">
  </script>
  <script>quizdown.register(quizdownHighlight).register(quizdownKatex).init()</script> 
  ...

</head>
```

You can either use a link to a CDN or download the `quizdown.js` file.

**Comment by bonartm** [comment]
I have [updated the installation instructions](https://github.com/bonartm/hugo-quiz/blob/master/README.md#installation). Please feel free to improve the documentation!
