### ISSUE TITLE
Error building site

### ISSUE THREAD

**Issue by NicolasStefaniak** [bonartm/hugo-quiz#9]
Hello,
Thanks for hugo quiz. 
first of all, I want to say that I am a beginner and I have perhaps missed something. I also want to state that I am not able to determine whether my problem is due to hugo-quiz or blogdown. 

I have tried to install hugo-quiz using blogdown (from Rstudio team). 
Here are the steps that I have followed:
**Firstly**, create blogdown with the hugo-theme-learn 
This step works. 
**Secondly** Try to modify some content 
I have created new md files, and Rmarkdown files. 
This step works. 
**Thirdly**
I have added the custom-header.html file in the directory ./layouts/partials/custom-header.html
and the "quidown.html" file in the ./layouts/shortcodes
I run the local server. It works. 
**Fourthly**
I add a markdown file with a quiz in the directory :  
./content/basics/Statistiques/Quizz
I first added the file while the local server was on. I could have a quiz. 
However, when I stopped the server and try to serve anew the site, it does not work anymore and I receive an error message instead.  

```
".\content\basics\Statistiques\Quizz\index.md:1:1": unable to process menus for page "basics\\Statistiques\\Quizz\\index.md": invalid character 's' looking for beginning of value
Rebuild failed:

Logged 1 error(s)
```

I have tried several things : 
- delete the Quizz directory, serve site . Without the Quizz directory, the site works. 
- Add the directory 'Quizz' when the local server is off and serve site afteward, it does not work. 
- delete the Quizz directory, serve site, add the directory "Quizz" in the content directory, sometimes it works, sometimes it does not (and I cannot figure out why)

The file name is "index.md" 

The content of the file is exactly: 
```
---
title: "quizz test"
author: "NS"
date: "27/05/2022"
categories: ["R"]
tags: ["R Markdown", "Introduction", "Généralités"]
draft: false
images: []
menu:
  docs:
  parent: "statistiques"
weight: 100     
---
 

# Hugo Quiz
{{< quizdown >}}

---
primary_color: orange
secondary_color: lightgray
text_color: black
shuffle_questions: false
---
  
  ## The sound of dog
  
  ---
  shuffle_answers: false
---
  
  What do dogs sound like?
  
  > Some hint

- [ ] yes
- [ ] no
- [ ] `self.sound = "meow"`
- [x] wuff

## Put the [days](https://en.wikipedia.org/wiki/Day) in order!

> Monday is the *first* day of the week.

1. Monday
2. Tuesday
3. Wednesday
4. Friday
5. Saturday  
{{< /quizdown >}}
```

**Comment by bonartm** [comment]
Hi, thanks for using the project :)

 I tested the demo page with blogdown and hugo-learn theme and it works fine. The issue here is not quizdown but the entry:

```
menu:
  docs:
  parent: "statistiques"
```

in your page. When I remove this everything loads correctly.

**Comment by NicolasStefaniak** [comment]
Thanks a lot for the answer. I am going to try accordingly.
